name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: 
    - cron: '0 10,22 * * *'
env:
  CARGO_TERM_COLOR: always
  BDUSS:  ${{ secrets.BDUSS }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run
      run: cargo run --verbose --release
